app = "libretranslate-tuapp"

primary_region = "mad"

[build]
image = "libretranslate/libretranslate"

[env]
# Puedes definir idiomas por defecto o configuraciones extra aquí

[http_service]
internal_port = 5000
force_https = true
auto_start_machines = true
auto_stop_machines = true
min_machines_running = 0

[mounts]
source = "libretranslate_data"
destination = "/app/data"
